[package]
authors = ["eric@harris-braun.com"]
edition = "2018"
name = "profiles_coordinator"
version = "0.0.1-alpha1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profiles_coordinator"

[dependencies]
chrono = "=0.4.22"
serde = "=1.0.136"

hc_zome_profiles_coordinator = {git = "https://github.com/holochain-open-dev/profiles", branch = "for-hdk-v0.0.146", package = "hc_zome_profiles_coordinator"}